name: jsaction

on:
  push:

jobs:
  test-js-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: jsAction
        with:
          num1: 5
          num2: 10
      - run: echo ${{steps.jsAction.outputs.result}}